// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.7/mapgis/copyright.txt for details.
//>>built
define(["require","exports","./flatspecSpec","./flatspecAPI"],function(d,a,b,c){Object.defineProperty(a,"__esModule",{value:!0});a.scanSpec=b.scan;a.collectClassPathsSpec=b.collectClassPaths;a.scanAPI=c.scan;a.collectClassPathsAPI=c.collectClassPaths;a.schemaToClassModule={baseMap:"mapgis/Basemap",border:"mapgis/symbols/callouts/LineCallout3DBorder",callout:"mapgis/symbols/callouts/LineCallout3D",camera:"mapgis/Camera",classBreakInfo:"mapgis/renderers/support/ClassBreakInfo",classBreaksRenderer:"mapgis/renderers/ClassBreaksRenderer",
colorClassBreakInfo:"mapgis/renderers/support/pointCloud/ColorClassBreakInfo",colorModulationInfo:"mapgis/renderers/support/pointCloud/ColorModulation",colorStop:"mapgis/renderers/support/pointCloud/StopInfo",colorUniqueValueInfo:"mapgis/renderers/support/pointCloud/ColorUniqueValueInfo",csvLayer:"mapgis/layers/CSVLayer",description:"mapgis/webscene/support/Description",elevationInfo:"mapgis/layers/support/ElevationInfo",elevationLayer:"mapgis/layers/ElevationLayer",environment:"mapgis/webscene/Environment",extent:"mapgis/geometry/Extent",
extrudeSymbol3DLayer:"mapgis/symbols/ExtrudeSymbol3DLayer",featureLayer:"mapgis/layers/FeatureLayer",featureReduction_select:"mapgis/layers/support/FeatureReductionSelection",fillSymbol3DLayer:"mapgis/symbols/FillSymbol3DLayer",ground:"mapgis/Ground",groupLayer:"mapgis/layers/GroupLayer",heightModelInfo:"mapgis/geometry/HeightModelInfo",iconSymbol3DLayer:"mapgis/symbols/IconSymbol3DLayer",iconSymbol3DLayer_resource:"mapgis/symbols/support/IconSymbol3DLayerResource",imageServiceLayer:"mapgis/layers/ImageryLayer",integratedMeshLayer:"mapgis/layers/IntegratedMeshLayer",
labelingInfo:"mapgis/layers/support/LabelClass",lighting:"mapgis/webscene/Lighting",lineSymbol3D:"mapgis/symbols/LineSymbol3D",lineSymbol3DLayer:"mapgis/symbols/LineSymbol3DLayer",lod:"mapgis/layers/support/LOD",mapServiceLayer:"mapgis/layers/MapImageLayer",material:"mapgis/symbols/support/Symbol3DFillMaterial",meshSymbol3D:"mapgis/symbols/MeshSymbol3D",mosaicRule:"mapgis/layers/support/MosaicRule",objectSymbol3DLayer:"mapgis/symbols/ObjectSymbol3DLayer",objectSymbol3DLayer_resource:"mapgis/symbols/support/Symbol3DResource",
openStreetMapLayer:"mapgis/layers/OpenStreetMapLayer",outline:"mapgis/symbols/support/Symbol3DOutline",pathSymbol3DLayer:"mapgis/symbols/PathSymbol3DLayer",point_geometry:"mapgis/geometry/Point",pointCloudClassBreaksRenderer:"mapgis/renderers/PointCloudClassBreaksRenderer",pointCloudFixedSizeAlgorithm:"mapgis/renderers/support/pointCloud/PointSizeFixedSizeAlgorithm",pointCloudLayer:"mapgis/layers/PointCloudLayer",pointCloudRGBRenderer:"mapgis/renderers/PointCloudRGBRenderer",pointCloudSplatAlgorithm:"mapgis/renderers/support/pointCloud/PointSizeSplatAlgorithm",
pointCloudStretchRenderer:"mapgis/renderers/PointCloudStretchRenderer",pointCloudUniqueValueRenderer:"mapgis/renderers/PointCloudUniqueValueRenderer",pointSymbol3D:"mapgis/symbols/PointSymbol3D",polygonSymbol3D:"mapgis/symbols/PolygonSymbol3D",popupInfo:"mapgis/PopupTemplate",presentation:"mapgis/webscene/Presentation",rendererLegendOptions:"mapgis/renderers/support/LegendOptions",renderingRule:"mapgis/layers/support/RasterFunction",sceneLayer:"mapgis/layers/SceneLayer",simpleRenderer:"mapgis/renderers/SimpleRenderer",
slide:"mapgis/webscene/Slide",spatialReference:"mapgis/SpatialReference",styleSymbolReference:"mapgis/symbols/WebStyleSymbol",thumbnail:"mapgis/webscene/support/Thumbnail",tiledImageServiceLayer:"mapgis/layers/TileLayer",tiledMapServiceLayer:"mapgis/layers/TileLayer",tileInfo:"mapgis/layers/support/TileInfo",title:"mapgis/webscene/support/Title",uniqueValueInfo:"mapgis/renderers/support/UniqueValueInfo",uniqueValueRenderer:"mapgis/renderers/UniqueValueRenderer",vectorTileLayer:"mapgis/layers/VectorTileLayer",verticalOffset:"mapgis/symbols/support/Symbol3DVerticalOffset",
viewpoint:"mapgis/Viewpoint",webScene:"mapgis/WebScene",webTiledLayer:"mapgis/layers/WebTileLayer",wmsLayer:"mapgis/layers/WMSLayer"}});