// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.7/mapgis/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper dojo/i18n!./DirectLineMeasurement3D/nls/DirectLineMeasurement3D ../core/accessorSupport/decorators ./Widget ./DirectLineMeasurement3D/DirectLineMeasurement3DViewModel ./support/widget".split(" "),function(q,r,n,d,e,b,p,l,a){return function(m){function c(a){a=m.call(this)||this;a.view=null;a.visible=null;a.viewModel=new l;a.unitOptions=null;return a}n(c,m);c.prototype.clearMeasurement=function(){};c.prototype.render=
function(){var c=this,d=!this.viewModel.isSupported,b="measuring"===this.viewModel.state,g=this.viewModel.measurement,k="ready"===this.viewModel.state?a.tsx("section",{key:"mapgis-direct-line-measurement-3d__hint",class:"mapgis-direct-line-measurement-3d__hint"},a.tsx("p",null,e.hint)):null,d=d?a.tsx("section",{key:"mapgis-direct-line-measurement-3d__unsupported",class:"mapgis-direct-line-measurement-3d__panel--error"},a.tsx("p",null,e.unsupported)):null,f=function(c,b,d){switch(b.state){case "available":return a.tsx("div",
{key:d+"-enabled",class:"mapgis-direct-line-measurement-3d__measurement-item"},a.tsx("span",{class:"mapgis-direct-line-measurement-3d__measurement-item-title"},c),a.tsx("span",{class:"mapgis-direct-line-measurement-3d__measurement-item-value"},b.text));case "unavailable":return a.tsx("div",{key:d+"-disabled",class:a.join("mapgis-direct-line-measurement-3d__measurement-item","mapgis-direct-line-measurement-3d__measurement-item--disabled")},a.tsx("span",{class:"mapgis-direct-line-measurement-3d__measurement-item-title"},
c))}},g=b?a.tsx("section",{key:"mapgis-direct-line-measurement-3d__measurement",class:"mapgis-direct-line-measurement-3d__measurement"},f(e.direct,g.directDistance,"direct"),f(e.horizontal,g.horizontalDistance,"horizontal"),f(e.vertical,g.verticalDistance,"vertical")):null,h=this.id+"__units",f=a.tsx("label",{class:"mapgis-direct-line-measurement-3d__units-label",for:h},e.unit),h=a.tsx("div",{class:"mapgis-direct-line-measurement-3d__units-select-wrapper"},a.tsx("select",{class:"mapgis-direct-line-measurement-3d__units-select mapgis-select",
id:h,onchange:this._changeUnit,bind:this},this.viewModel.unitOptions.map(function(b){return b===c.viewModel.unit?a.tsx("option",{key:b,value:b,selected:!0},e.units[b]):a.tsx("option",{key:b,value:b},e.units[b])}))),f=b?a.tsx("section",{key:"mapgis-direct-line-measurement-3d__units",class:"mapgis-direct-line-measurement-3d__units"},f,h):null,b=b?a.tsx("button",{class:a.join("mapgis-button","mapgis-direct-line-measurement-3d__clear-button"),bind:this,onclick:this._newMeasurement},e.newMeasurement):null,k=this.visible?
a.tsx("div",{class:"mapgis-direct-line-measurement-3d__container"},d,k,g,f,b):null;return a.tsx("div",{key:"",class:"mapgis-direct-line-measurement-3d mapgis-widget mapgis-widget--panel",role:"presentation"},k)};c.prototype._newMeasurement=function(){this.clearMeasurement()};c.prototype._changeUnit=function(a){a=a.target;if(a=a.options[a.selectedIndex])this.unit=a.value};d([b.aliasOf("viewModel.view")],c.prototype,"view",void 0);d([b.aliasOf("viewModel.visible"),a.renderable()],c.prototype,"visible",void 0);
d([b.property({type:l}),a.renderable(["viewModel.state","viewModel.unitOptions","viewModel.unit","viewModel.measurement"])],c.prototype,"viewModel",void 0);d([b.aliasOf("viewModel.unitOptions")],c.prototype,"unitOptions",void 0);d([b.aliasOf("viewModel.unit")],c.prototype,"unit",void 0);d([b.aliasOf("viewModel.clearMeasurement")],c.prototype,"clearMeasurement",null);d([a.accessibleHandler()],c.prototype,"_newMeasurement",null);d([a.accessibleHandler()],c.prototype,"_changeUnit",null);return c=d([b.subclass("mapgis.widgets.DirectLineMeasurement3D")],
c)}(b.declared(p))});